### ISSUE TITLE
Creation of missing directories

### ISSUE THREAD

**Issue by mbollmann** [neulab/xnmt#292]
XNMT appears to automatically create directory structures (if they don't exist yet) for model files and log files, but not for hypothesis files. When I use...

```yaml
example: !Experiment
  exp_global: !ExpGlobal
    model_file: models/{EXP}.model
    log_file: logs/{EXP}.logfile

...

  evaluate:
    - !AccuracyEvalTask
      eval_metrics: wer
      src_file: data/{EXP}/dev.orig
      ref_file: data/{EXP}/dev.norm
      hyp_file: outputs/{EXP}.dev_hyp
```

...the directories `models` and `logs` are created, but `outputs` is not (raising `FileNotFoundError` during the evaluation if it didn't exist yet).

I thought this was a bit unexpected.
