### ISSUE TITLE
Schedule metric usage unclear

### ISSUE THREAD

**Issue by msperber** [neulab/xnmt#293]
Currently, the evaluator that appears first among all dev evaluators is used to determine the schedule (early stopping, patience), which is an important feature but it's not documented anywhere. It should either be documented or be configurable in the config file. In #260 there was a plan to make this even more flexible using something like: 
```
  train: !SimpleTrainingRegimen
    ..
    dev_tasks:
      - !AccuracyEvalTask
        model: *mt_model
        eval_metrics: bleu
        src_file: mt-dev.src
        trg_file: mt-dev.trg
      - !AccuracyEvalTask
        model: *pos_model
        eval_metrics: wer
        src_file: pos-dev.src
        trg_file: pos-dev.trg
    eval_combinator: "x[0]-x[1]"
```
