### ISSUE TITLE
!Repeat syntax

### ISSUE THREAD

**Issue by msperber** [neulab/xnmt#467]
A ```!Repeat``` syntax would allow specifying multilayer architectures where the same layer spec is repeated several times in a less annoying way. The idea would be to resolve this in the preloading step. A draft syntax would be:
```
!Repeat
  times: 6
  shared: False
  content: !ModularSeqTransducer
    modules:
    - ResidualSeqTransducer { ... }
    - ResidualSeqTransducer { ... }
```
