### ISSUE TITLE
Removal of include_vocab_reference option in PlainTextReader 

### ISSUE THREAD

**Issue by pierregodard** [neulab/xnmt#476]
PR #445 removed the `include_vocab_reference` option for `PlainTextReader` that I've been relying on for some experiments.

@msperber: could you tell me a bit more about the motivation behind this and if I can revert locally to the previous state without breaking something else in the current master branch? 

You say it was previously discussed that "it would better be solved by specifying a reference to the vocab in the component that actually needs to know the vocab". I've been using the `include_vocab_reference` option in the `DefaultTranslator` where I need to have access to the lexical form of the words. The reference to the vocabulary used to be specified this: 

```yaml
model: !DefaultTranslator
  src_reader: !PlainTextReader
    vocab: !Vocab {vocab_file: '/path/to/my.vocab'}
    include_vocab_reference: True
```

but I am not sure what the interface should now look like then. Is it more desirable to have to specify the vocabulary in (potentially) multiple places, rather than having the previous mechanism where `SimpleSentenceInput` could keep a reference to the vocabulary?

Thank you for your help!
