### ISSUE TITLE
Can't decode with existing model if experiment is done?

### ISSUE THREAD

**Issue by philip30** [neulab/xnmt#533]
Maybe is it because of the experiments.status == "done" already? For example, the example 08_load_eval_beam is not working either. So do the other finetuning examples I guess.

**Comment by msperber** [comment]
Yeah, this is definitely related to the status flag, which is intended to seamlessly continue failed experiments (but not fully implemented yet). There's a couple of ways around it:
- use ```!LoadSerialized``` to load only the model, not the whole experiment. That would probably be the most intuitive way to do things
- load the whole experiment, but overwrite the status (however, you would probably also need to set ```train: ~``` or ```run_for_epochs: 0``` or something like that. This is a bit less intuitive, but in the case of multitask learning with several models this is sometimes the easiest way.
- move the status fields inside preproc runner, train, evaluate, so each of them keeps their own status. That way, one could load the whole experiment and then only overwrite the ```evaluate``` field with some new evaluators, and running the experiment would skip the preprocessing and training and jump right to the new evaluation.

**Comment by anbasile** [comment]
Are there any proofed solutions to this issue? I have a multi-task model and with the following configuration I can't force the model to evaluate.

```
inference-mtl: !LoadSerialized
  filename: ./results/char2-mtl.mod
  overwrite:
  - path: status
    val: null
  - path: train.tasks.0.run_for_epochs
    val: 0
  - path: train.tasks.1.run_for_epochs
    val: 0
  - path: train.tasks.0.dev_tasks
    val:
    - !AccuracyEvalTask
      # model: !Ref { name: first_task_model }
      inference: !AutoRegressiveInference {}
      eval_metrics: bleu,gleu
      src_file: './head.src.dev'
      ref_file: './head.tgt.dev'

```

**Comment by msperber** [comment]
Dev eval tasks are only computed during training, but training is skipped because there are 0 epochs. You probably want to replace ``path: train.tasks.0.dev_tasks`` by ``path: evaluate`` to use the evaluation step that is carried out after training.

**Comment by anbasile** [comment]
Thanks for the comment. After some trial and error, I've solved the issue with the following configuration. I have also been able to correctly modify some settings, like adding beam search. This is decoding from a checkpoint.
                                                                                                                                     
```
inference-mtl: !LoadSerialized
  filename: ./results/char2-mtl.mod
  overwrite:
  - path: train.tasks.0.run_for_epochs
    val: 0
  - path: train.tasks.0.model.inference.search_strategy.one_best
    val: false
  - path: evaluate
    val:
    - !AccuracyEvalTask
      model: !Ref { path: train.tasks.0.model }
      inference: !AutoRegressiveInference
        search_strategy: !BeamSearch
          beam_size: 10
          one_best: false
      eval_metrics: bleu,gleu
      src_file: './head.src.dev'
      ref_file: './head.tgt.dev'
      hyp_file: './out'

```
