### ISSUE TITLE
Char2Char model

### ISSUE THREAD

**Issue by anbasile** [neulab/xnmt#540]
I am trying to use xNMT to replicate [recent results](https://github.com/anbasile/sigdialSubmission) on the E2E Challenge.

Basically, I am trying to build a character-2-character attention model, as it is described in [this tf configuration](https://github.com/anbasile/sigdialSubmission/blob/master/model/training/nmt_medium.yml).

This is my best attempt:

```
!Experiment
  name: NLG-e2e
  # global parameters shared throughout the experiment
  exp_global: !ExpGlobal
    model_file: '{EXP_DIR}/models/{EXP}.mod'
    log_file: '{EXP_DIR}/logs/{EXP}.log'
    default_layer_dim: 512
    dropout: 0.3
  # model architecture
  model: !DefaultTranslator
    src_reader: !CharFromWordTextReader
      vocab: !Vocab {vocab_file: src.charvocab}
    trg_reader: !CharFromWordTextReader
      vocab: !Vocab {vocab_file: tgt.charvocab}
      output_proc: join-char
    encoder: !SegmentingSeqTransducer
      segment_composer: !CharNGramComposer
        ngram_size: 4
        word_vocab: !Vocab {vocab_file: src.ngramcount}
      final_transducer: !BiLSTMSeqTransducer {}
    attender: !MlpAttender
      hidden_dim: 512
      state_dim: 512
      input_dim: 512
  # training parameters
  train: !SimpleTrainingRegimen
    run_for_epochs: 20
    initial_patience: 2
    patience: 1
    lr_decay: 0.5
    lr_decay_times: 2
    max_src_len: 400
    max_trg_len: 400
    batcher: !SrcBatcher
      batch_size: 32
    trainer: !AdamTrainer
      alpha: 0.001
    src_file: src-train-toy.txt
    trg_file: tgt-train-toy.txt
    dev_tasks:
      - !LossEvalTask
        src_file: src-dev-toy.txt
        ref_file: tgt-dev-toy.txt
  # final evaluation
  evaluate:
    - !AccuracyEvalTask
      eval_metrics: bleu
      src_file: src-test-toy.txt
      ref_file: tgt-test-toy.txt
      hyp_file: ./output/{EXP}.test_hyp
```

I've tried to overfit the model on a small data set, with mixed results. Any help, especially regarding input segmentation, would be appreciated.
